export const reducerCases = {
  CREATE_NEW_CHAT: "CREATE_NEW_CHAT",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGES: "ADD_MESSAGES",
  SET_MESSAGE_SEARCH: "SET_MESSAGE_SEARCH",
  SET_USER_MESSAGE_LIST: "SET_USER_MESSAGE_LIST"
}