export const reducerCases = {
  CREATE_NEW_CHAT: "CREATE_NEW_CHAT",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGES: "ADD_MESSAGES",
  SET_MESSAGE_SEARCH: "SET_MESSAGE_SEARCH",
  SET_USER_MESSAGE_LIST: "SET_USER_MESSAGE_LIST",
  // 通话相关
  SET_VIDEO_CALL: " SET_VIDEO_CALL",
  SET_VOICE_CALL: "SET_VOICE_CALL",
  SET_INCOMING_VIDEO_CALL: "SET_INCOMING_VIDEO_CALL",
  SET_INCOMING_VOICE_CALL: "SET_INCOMING_VOICE_CALL",
  END_CALL: "END CALL",
  // 是否接听
  IS_CONNECT: "IS_CONNECT",
}